start_step_id: 0

step_lst:
  - step_id: 0
    text: "story for step 0"
    actions:
      - type: "select"
        id: 0
        value_lst:
          - label: "do it1"
            value: "value2"
            results:
              - type: "go_to"
                next_step_id: 1
              - type: "loot"
                id: "spoon"
              - type: "expereance"
                var: "Daria.respect"
                operation: "add"
                value: 100
              - type: "expereance"
                var: "Nikita.respect"
                operation: "sub"
                value: 100
      - label: "do it2"
        value: "value1"
        results:
          - type: "go_to"
            next_step_id: 2
  - step_id: 1
    text: "story for step 1"
    actions:
      type: "select"
      id: 0
      value_lst:
        - label: "do it1"
          value: "value1"
          results:
            - type: "go_to"
              next_step_id: 3
        - label: "do it2"
          value: "value2"
          results:
            - type: "go_to"
              next_step_id: 3
  - step_id: 2
    text: "story for step 2"
    actions:
      - type: "select"
        id: 0
        value_lst:
          - label: "do it1"
            value: "value2"
            results:
              - type: "go_to"
                next_step_id: 3
          - label: "do it2"
            value: "value1"
            results:
              - type: "go_to"
                next_step_id: 3
  - step_id:
    text: "End of game!"
    is_finish_step: true
